// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type StatusType string

const (
	StatusTypeOngoing   StatusType = "ongoing"
	StatusTypeCompleted StatusType = "completed"
	StatusTypeDropped   StatusType = "dropped"
)

func (e *StatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusType(s)
	case string:
		*e = StatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusType: %T", src)
	}
	return nil
}

type NullStatusType struct {
	StatusType StatusType `json:"status_type"`
	Valid      bool       `json:"valid"` // Valid is true if StatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.StatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusType), nil
}

type UserRole string

const (
	UserRoleUser      UserRole = "user"
	UserRoleAdmin     UserRole = "admin"
	UserRoleModerator UserRole = "moderator"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Author struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type AuthorComic struct {
	AuthorID int32 `json:"author_id"`
	ComicID  int32 `json:"comic_id"`
}

type Bookmark struct {
	UserID  int32 `json:"user_id"`
	ComicID int32 `json:"comic_id"`
}

type Chapter struct {
	ID            int32            `json:"id"`
	ComicID       *int32           `json:"comic_id"`
	ChapterNumber int32            `json:"chapter_number"`
	Title         *string          `json:"title"`
	ContentUrl    *string          `json:"content_url"`
	ReleaseDate   pgtype.Timestamp `json:"release_date"`
}

type Comic struct {
	ID            int32            `json:"id"`
	Slug          *string          `json:"slug"`
	Title         string           `json:"title"`
	Status        StatusType       `json:"status"`
	Summary       *string          `json:"summary"`
	ReleaseDate   pgtype.Date      `json:"release_date"`
	CoverImageUrl *string          `json:"cover_image_url"`
	UploadDate    pgtype.Timestamp `json:"upload_date"`
}

type ComicGenre struct {
	ComicID int32 `json:"comic_id"`
	GenreID int32 `json:"genre_id"`
}

type Genre struct {
	ID        int32  `json:"id"`
	GenreName string `json:"genre_name"`
}

type Session struct {
	SessionID    int32            `json:"session_id"`
	UserID       *int32           `json:"user_id"`
	SessionToken string           `json:"session_token"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	IsActive     *bool            `json:"is_active"`
}

type User struct {
	UserID      int32            `json:"user_id"`
	Username    string           `json:"username"`
	Email       string           `json:"email"`
	Password    string           `json:"password"`
	FirstName   *string          `json:"first_name"`
	LastName    *string          `json:"last_name"`
	DateOfBirth pgtype.Date      `json:"date_of_birth"`
	Role        UserRole         `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
